public class Constants {
    
    	//for loan Account loan status
    	public static final string LOAN_STATUS_IN_APPROVAL = 'In Approval' ;
    	public static final string LOAN_STATUS_APPROVED = 'Approved' ;
        public static final string LOAN_STATUS_IN_REPAYMENT = 'In Repayment' ;
        public static final string LOAN_STATUS_TERM_COMPLETE = 'Term Complete' ;
    	public static final string LOAN_STATUS_GOOD_STANDING = 'Good - Standing' ;
        public static final string LOAN_STATUS_PAST_DUE = 'Past Due';
        public static final string LOAN_STATUS_CLOSED_OBLIGATION_MET = 'Closed - Obligations met';
    	
    	//for loan frequency..
    	public static final string LOAN_FREQUENCY_DAILY = 'Daily';
    	public static final string LOAN_FREQUENCY_WEEKLY = 'Weekly';
    	public static final string LOAN_FREQUENCY_MONTHLY = 'Monthly';
    	
    	//Application statuses
    	public static final string DOCUMENT_UPLOAD = 'Document Upload Complete';
    
    	//for Underwriting department
    	public static final string IN_REVIEW = 'In Review';
    
    }